### ISSUE TITLE
Añadir keynotes basados en el diseño maqueta

### ISSUE THREAD

**Issue by goanpeca** [PyConColombia/website-2019#11]
@aerendon los archivos están en `/diseño/Look and feel.ai`

**Comment by arendondiosa** [comment]
![image](https://user-images.githubusercontent.com/14989202/44958342-9c014a80-aea4-11e8-893c-8af5ba68ecb9.png)

![image](https://user-images.githubusercontent.com/14989202/44958350-b3d8ce80-aea4-11e8-9180-c174469c3087.png)

Para keynotes usé el mismo modelo de `speaker` comprobando con el booleano si es keynote.
Separé por dos urls: `/keynotes` y `/speakers`

Queda pendiente agregar diseño ya que aún no está disponible en drive.

**Comment by arendondiosa** [comment]
Jessica McKellar:
- Founder and CTO at Pilot
- Former Vp of Engineering
at Dropbox

Carol Willing:
- Research Software Engineer, Project Jupyter
-  Python Core Developer and PSF Fellow

Ola Sendecka:
- Django project core member,
- django girls co-founder

3. Agregar keynote:
Russell Keith-Magee
- Founder BeeWare Project
- Former Core Developer Django
