### ISSUE TITLE
Información adicional para el venue

### ISSUE THREAD

**Issue by pyjavo** [PyConColombia/website-2019#137]
1. Datos de como llegar a la Javeriana desde el aeropuerto, desde la terminal
2. Lugares turísticos de Bogota o enlaces hacia mayor información

**Comment by pyjavo** [comment]
1. 
Se seleccionaron las rutas más rápidas sin transbordo para conveniencia

<img width="911" alt="captura de pantalla 2019-01-16 a las 3 43 44 p m" src="https://user-images.githubusercontent.com/3085051/51277639-3373bf80-19a6-11e9-88e1-9e46e5aa670a.png">

**Comment by arendondiosa** [comment]
@javierdaza este issue lo va a solucionar usted?
(Lo siento pero eso entiendo entonces es mejor estar seguro :sweat_smile: )

**Comment by pyjavo** [comment]
jajajaja es que pensaba buscar más información pero creo que sería solo eso por ahora. Hágale usted.
