### ISSUE TITLE
modificar datos speaker Jorge Gonzalez

### ISSUE THREAD

**Issue by JorgeMrtnzG** [PyConColombia/website-2019#148]
**Cargo:**  Solutions Engineer, Geotab
**Descripcion:** Jorge Gonzalez is a Solutions Engineer who has contributed to the development and implementation of Big Data in Geotab Europe.
He started in Geotab in June 2016, before finalising his degree in Telecommunications engineering. After writing and publishing his thesis he stayed in Geotab headquarters in Canada for two months working directly with the Big Data/Data & Analytics team taking part in the development of data.geotab.com.
Jorge continues enrich his data analysis and data engineering knowledge to ensure the advancement of Geotab as a leader in the data science. He currently leads Geotab data initiatives in Europe. 
Apart from work, Jorge is dedicated to rugby. He plays at Club de Rugby Cisneros in Madrid since he was 12 years old. He currently plays in the first Spanish league.    
**Image url:** https://gm1.ggpht.com/bTpfUDZ33WFM3BdkgarGVfG8IzM-MDfLg8RC7fxnaW6fzB3ZOgGHHVvFM3qxSpyPVPNCRrkMlVMVF9k7w8404v7CLEx52ALt0Um4YJahBxSbfEHQoGEg2dTxiXWS2ooRnh4wqGuQDbL0BXZAMKdfBaKjIfyA8O32vh-swVuLUkZRow9n_UtOCXYFVkjmuL3kFEYAkrOBcSNKSldEpChVvOt0s3J7hDaBGFzpBV70JCR6tVIqcIdl0PczjbsC2y9buX5zWjxS3O7FtH25Wwdj6BL6yB69Tty4MKytewkEdXNJni-G50yuNCoBkwFVAusIWq8U4-Oqxx0nzV42LN6YhKbv6-mup312-ba6zdXFlOxmQDg6C4hN7TqEgnTUqa_j6if4byNuWPJgk-7hhPT7n8KQvf8xBglJsWPEmOVhRMyF0-AnpeYlez2TkVfbsymUe3GSpFhlhKUfaJt5pp_AgSpMcYFws0OIuVjQWGhwp7-W4DLxF4I8VzU-zliDWOjbjgzMf6FhVjkYVJ7XloTYU_iLgGc6zwMB5JGus4de8zvEPGhrHLfskzVuKubKoU3L2J3EaV_cgFYouhJlk950wVJHC104NbFroOiTWXcDoRf_FO3X7CKmKTRoPSHNr_vk2HiwbDziRgeh8vOhA4JpXLRxuG8Xt5ivzzb6JrR3YzE9Xb8pmHdWqDngKJP3oEXt283Vh8JpSxfPSwZBK8_37BnTyWmriOU=s0-l75-ft-l75-ft

**Comment by arendondiosa** [comment]
@JorgeMartinezG la imagen no existe/me muestra un link no accesible
