### ISSUE TITLE
Agregar sitio 2020 a Navbar

### ISSUE THREAD

**Issue by arendondiosa** [PyConColombia/website-2019#165]
_Prerrequisito: Preguntar a @goanpeca si https://2020.pycon.co está habilitado_

**Comment by goanpeca** [comment]
Hmmmmm tendría que poner una regla de redirección en cloudfare porque github pages no permite manejar dos cnames

**Comment by goanpeca** [comment]
Fixed by https://github.com/PyConColombia/website-2019/commit/275ced584b8af7a60eecb8e41b80bd01c914e546
