### ISSUE TITLE
Ocultar “compra tu entrada” Web Pycon 2019

### ISSUE THREAD

**Issue by leonartromo** [PyConColombia/website-2019#166]
Se requiere que se oculte el Botón de "COMPRA TU ENTRADA" ya que se encuentra visible en la pagina web de PyCon Colombia 2019.

https://2019.pycon.co/

**Comment by goanpeca** [comment]
Fixed by https://github.com/PyConColombia/website-2019/commit/275ced584b8af7a60eecb8e41b80bd01c914e546
