### ISSUE TITLE
Ocultar “Buy Tickets Now” Web Pycon 2018

### ISSUE THREAD

**Issue by leonartromo** [PyConColombia/website-2019#167]
Se requiere que se oculte el Botón de "Buy Tickets Now" ya que se encuentra visible en la pagina web de PyCon Colombia 2018.

https://2018.pycon.co/

**Comment by goanpeca** [comment]
Hola @leonartromo, por favor abre este _issue_ en 

https://github.com/PyConColombia/website-2018/issues/ ya que hace referencia a https://2018.pycon.co/
