### ISSUE TITLE
Ocultar “Few tickets left get yours!” Web Pycon 2017

### ISSUE THREAD

**Issue by leonartromo** [PyConColombia/website-2019#168]
Se requiere que se oculte el Botón de "Few tickets left get yours!" ya que se encuentra visible en la pagina web de PyCon Colombia 2017.

https://2017.pycon.co/

**Comment by goanpeca** [comment]
Hola @leonartromo, por favor abre este _issue_ en 

https://github.com/PyConColombia/website-2017/issues/ ya que hace referencia a https://2017.pycon.co/
