### ISSUE TITLE
En móvil se ve extraño la sección de keynotes

### ISSUE THREAD

**Issue by pyjavo** [PyConColombia/website-2019#26]
Esta desordenado. Salen descripciones o fotos pegadas una tras de otra

**Comment by javierdaza** [comment]
![screenshot_20180926-091336](https://user-images.githubusercontent.com/3085051/46086046-f2dd0580-c16c-11e8-8df1-24e4632a73ec.png)

![screenshot_20180926-091336](https://user-images.githubusercontent.com/3085051/46086083-05573f00-c16d-11e8-8fcb-55ec4a2a274c.png)

**Comment by pyjavo** [comment]
![screenshot_20180926-091343](https://user-images.githubusercontent.com/3085051/46086145-1a33d280-c16d-11e8-8257-f12f2209a035.png)
![screenshot_20180926-091336](https://user-images.githubusercontent.com/3085051/46086157-1f911d00-c16d-11e8-8374-ccc87d16d88b.png)
