### ISSUE TITLE
Amistosa con SEO

### ISSUE THREAD

**Issue by pyjavo** [PyConColombia/website-2019#27]
Para que la pagina sea mas amigable con el SEO, sugiero que las paginas de cada keynote speaker sean por ejemplo:

- https://www.pycon.co/keynotes/benjamin-lewis
- https://www.pycon.co/keynotes/ola-sendecka

De esta forma se tendrán mas páginas indexadas en los buscadores

**Comment by arendondiosa** [comment]
@javierdaza no sé si ya vió que las páginas individuales existen (Es más, esos enlaces del comentario están funcionando) :smile: 

En el diseño original estaba así: Como una visión rápida del speaker, además de tener a parte la vista de cada uno
