### ISSUE TITLE
Equipo PyCon 2019

### ISSUE THREAD

**Issue by arendondiosa** [PyConColombia/website-2019#46]
Conformar Equipo 2019 para la Web

## Organizadores

- [X] John Jairo Roa
  - [x] _Web:_ https://about.me/jhonjairoroa87
  - [x] _Email:_ john@pycon.co
  - [x] _Facebook:_ https://www.facebook.com/johnroa87
  - [x] _Twitter:_ https://twitter.com/jhonjairoroa87
  - [x] _Github:- https://github.com/jhonjairoroa87
  - [x] _Equipo:_ Chief Organizer
- [X] Johana Sanchez
  - [ ] _Web_:
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [X] _Foto_:
  - [x] _Equipo_: Social Media y Django Girls
- [X] Gonzalo Peña
  - [x] _Web_: http://goanpeca.co
  - [x] _Email_: goanpeca@gmail.com
  - [X] _Facebook_: goanpeca
  - [X] _Twitter_: goanpeca
  - [X] _Github_: goanpeca
  - [X] _Foto_: https://www.python.org.co/usuarios/goanpeca
  - [X] _Equipo_: Keynotes, Sitio Web
- [X] Alejandro E. Rendon
  - [X] _Web_: http://rendon.co
  - [X] _Email_: alejandro@rendon.co
  - [x] _Facebook_:
  - [x] _Twitter_:
  - [X] _Github_: aerendon
  - [X] _Foto_:
  - [X] _Equipo_: Sitio Web
- [X] Carlos Andrés Sierra
  - [ ] _Web_: 
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [X] _Foto_:
  - [X] _Equipo_: Speakers
- [X] Jorge Martínez Gómez
  - [ ] _Web_: 
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [X] _Foto_:
  - [X] _Equipo_: Speakers
- [X] Juan David Hernandez Giraldo
  - [ ] _Web_: 
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [X] _Foto_:
  - [x] _Equipo_: Speakers
- [x] Milton Lenis
  - [x] _Web_: https://www.miltonlenis.com
  - [x] _Email_: miltonln04@gmail.com
  - [x] _Twitter_: https://twitter.com/MiltonLn
  - [x] _Github_: https://github.com/MiltonLn
  - [x] _Foto_: https://pbs.twimg.com/profile_images/958855724410470400/2CYhgILM_400x400.jpg
  - [x] _Equipo_: Speakers
- [X] Javier Daza Comas
  - [x] _Web_: https://javierdaza.co/
  - [x] _Twitter_: https://twitter.com/javidazac
  - [x] _Github_: https://github.com/javierdaza
  - [x] _Equipo_: Django Girls, Keynotes
- [x] Esteban Maya Cadavid
  - [ ] _Linkedin_:  https://www.linkedin.com/in/esteban-maya-cadavid-10346051/
  - [x] _Email_: emayacadavid9@gmail.com
  - [x] _Foto_: https://www.python.org.co/usuarios/estebanx64/esteban-maya.jpg
  - [x] _Equipo_: Speakers

## Colaboradores

- [x] Carolina Gómez Trejos
  - [x] _Web_: https://carogomezt.github.io/
  - [x] _Email_: carolina9511@gmail.com
  - [x] _Facebook_: https://www.facebook.com/carogomezt
  - [x] _Twitter_: https://twitter.com/caro_gomezt
  - [x] _Github_: https://github.com/carogomezt
  - [x] _Foto_: https://www.python.org.co/usuarios/carogomezt//carogomezt.jpg
  - [x] _Equipo_: Redes Sociales, After Party :-p
- [x] Manuela Ocampo
  - [ ] _Web_: 
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [ ] _Foto_:
  - [ ] _Equipo_:
- [x] Nicolas Roa
  - [ ] _Linkedin:_ https://www.linkedin.com/in/nicolas-roa-r/
  - [x] _Email:_ nicolas.rrodriguez16@gmail.com
  - [x] _Facebook:_ https://www.facebook.com/nicolas.roarodriguez
  - [x] _Twitter:_ https://twitter.com/nico_roa26
  - [x] _Github:_ https://github.com/nicolasroa26
  - [x] _Foto:_ https://drive.google.com/file/d/1A6c8rf3veFm4aTbgwqkDQFzoMxEp4XSq/view?usp=sharing
  - [x] _Equipo:_ Difusion
- [x] Edwin Jerez
  - [ ] _Web_: 
  - [ ] _Email_:
  - [ ] _Facebook_:
  - [ ] _Twitter_:
  - [ ] _Github_:
  - [ ] _Foto_:
  - [ ] _Equipo_:
- [x] Isabella Quintana
  - [x] *Web*: isabellaquintana.com
  - [ ] *Email*:
  - [x] *Facebook*: https://www.facebook.com/isaquinva
  - [x] *Twitter*: https://twitter.com/isaquinva 
  - [x] *Github*: https://github.com/isaquinva
  - [ ] *Linkedin*: https://www.linkedin.com/pub/isabella-quintana/a1/662/72a
  - [ ] *Foto*: https://www.dropbox.com/s/oy9fzohmrypgnn9/profile-500px.jpg?dl=0

## Voluntarios

- [ ] V1
- [ ] V2

**Comment by estebanx64** [comment]
Organizadores

Esteban Maya Cadavid
Web: 
Email: emayacadavid9@gmail.com
Facebook: 
Twitter:
Github:
Foto:
Equipo: Speakers

**Comment by pyjavo** [comment]
Javier Daza Comas
 Web: https://javierdaza.co/
 Twitter: https://twitter.com/javidazac
 Github: https://github.com/javierdaza
 Equipo: Django Girls, Keynotes

**Comment by estebanx64** [comment]
Organizadores
Esteban Maya Cadavid
linkedin: https://www.linkedin.com/in/esteban-maya-cadavid-10346051/
Email: emayacadavid9@gmail.com
Foto: https://www.python.org.co/usuarios/estebanx64/esteban-maya.jpg
Equipo: Speakers

**Comment by carogomezt** [comment]
Colaboradores
Carolina Gómez Trejos
 Web: https://carogomezt.github.io/
 Email: carolina9511@gmail.com
 Facebook: https://www.facebook.com/carogomezt
 Twitter: https://twitter.com/caro_gomezt
 Github: https://github.com/carogomezt
 Foto: https://www.python.org.co/usuarios/carogomezt//carogomezt.jpg
 Equipo: Redes Sociales

**Comment by MiltonLn** [comment]
Milton Lenis
Web: https://www.miltonlenis.com
Email: miltonln04@gmail.com
Twitter: https://twitter.com/MiltonLn
Github: https://github.com/MiltonLn
Foto: https://pbs.twimg.com/profile_images/958855724410470400/2CYhgILM_400x400.jpg
Equipo: Speakers

**Comment by nicolasroa26** [comment]
John Jairo Roa
Chief Organizer
 Web: https://about.me/jhonjairoroa87
 Email: john@pycon.co
 Facebook: https://www.facebook.com/johnroa87
 Twitter: https://twitter.com/jhonjairoroa87
 Github: https://github.com/jhonjairoroa87

**Comment by nicolasroa26** [comment]
Nicolas Roa
 Linkedin: https://www.linkedin.com/in/nicolas-roa-r/
 Email: nicolas.rrodriguez16@gmail.com
 Facebook: https://www.facebook.com/nicolas.roarodriguez
 Twitter: https://twitter.com/nico_roa26
 Github: https://github.com/nicolasroa26
 Foto: https://drive.google.com/file/d/1A6c8rf3veFm4aTbgwqkDQFzoMxEp4XSq/view?usp=sharing
 Equipo: Difusion

**Comment by pyjavo** [comment]
Para Edwin Jerez se puede usar la información del año pasado:
https://2018.pycon.co/team/edwin-jerez/edwin-jerez.jpg

https://2018.pycon.co/team/edwin-jerez/
