### ISSUE TITLE
Agregar websites de años anteriores

### ISSUE THREAD

**Issue by nicolasroa26** [PyConColombia/website-2019#53]
El usuario debería poder acceder a las paginas de años anteriores

**Comment by goanpeca** [comment]
@aerendon @soyelhijo mientras sean pocos años esto podría ir en el el pie de página, pero pensando a futuro, cual creen que podría ser una forma alternativa?

**Comment by arendondiosa** [comment]
Yo creo que puede ser un dropDown junto al idioma.
Si crece mucho puede considerarse una vista sólo para eso (Más de 10 elementos)
