### ISSUE TITLE
Crear modelo para sponsor

### ISSUE THREAD

**Issue by arendondiosa** [PyConColombia/website-2019#55]
Crear en lektor modelo de Sponsor

**Comment by goanpeca** [comment]
@aerendon nos podemos basar del sitio del año pasado, no?

**Comment by arendondiosa** [comment]
@goanpeca bueno, sería adaptarlo de acuerdo a la propuesta 2019, ya que hay pequeños cambios (Por ejemplo los niveles) 😝
