### ISSUE TITLE
Sugerencias de Google

### ISSUE THREAD

**Issue by goanpeca** [PyConColombia/website-2019#68]
<img width="626" alt="screen shot 2018-11-07 at 11 13 10" src="https://user-images.githubusercontent.com/3627835/48144206-7286e580-e27e-11e8-99d0-34fb2cabcecc.png">

**Comment by arendondiosa** [comment]
@goanpeca estuve mirando esta herramienta de google, y da un buen [resultado](https://search.google.com/test/mobile-friendly?id=0FRDqMrxAGZPm14GJjJR3A)

**Comment by goanpeca** [comment]
Dale @aerendon de una

mira esto

https://search.google.com/test/mobile-friendly?view=fetch-info&id=0FRDqMrxAGZPm14GJjJR3A

**Comment by arendondiosa** [comment]
![image](https://user-images.githubusercontent.com/14989202/49687773-e6164f80-fad5-11e8-98c5-795c26002325.png)
